# Generated by Django 4.1.1 on 2022-11-08 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('dueno', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRecibida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='')),
                ('recibidor', models.CharField(max_length=50)),
                ('remitente', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('NR', 'No recibido'), ('R', 'Recibido')], default='NR', max_length=2)),
                ('destinatario', models.CharField(max_length=50)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
