# Generated by Django 4.1.2 on 2022-11-12 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_correspondencia_conserje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='conserje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Conserjes', to=settings.AUTH_USER_MODEL),
        ),
    ]
