# Generated by Django 4.1.2 on 2022-11-13 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_correspondencia_conserje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='conserje',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Conserjes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Conserjes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.residencia'),
        ),
    ]
