# Generated by Django 4.1.2 on 2022-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_correspondencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('NR', 'No Recibido'), ('R', 'Recibido')], default='NR', max_length=15),
        ),
    ]
